# Generated by Django 4.1.2 on 2022-11-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainproduct', to='accounts.product')),
                ('relatedproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedproduct', to='accounts.product')),
            ],
        ),
    ]
