# Generated by Django 4.1.2 on 2022-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recommendedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relatedproduct',
            field=models.ManyToManyField(to='accounts.product'),
        ),
        migrations.DeleteModel(
            name='RecommendedProducts',
        ),
    ]
