# Generated by Django 4.1.2 on 2022-11-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_relatedproduct_delete_recommendedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='relatedproduct',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.product'),
        ),
    ]
