# Generated by Django 4.0 on 2022-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_product_relatedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartObject',
            field=models.ManyToManyField(to='accounts.cartObject'),
        ),
        migrations.AlterField(
            model_name='product',
            name='relatedproduct',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Product'),
        ),
    ]
