# Generated by Django 4.0 on 2022-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_placedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='paymentObject',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
