# Generated by Django 4.1.2 on 2022-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_placedorder_paymentobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Indoor Plant', 'indoor plant'), ('Native plant', 'native plant'), ('Pots', 'pots'), ('Fertilizer', 'fertilizer')], max_length=200),
        ),
    ]
